# Generated by Django 6.1.1 on 2026-09-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hot'), ('COOL', 'Cool'), ('SNACKS', 'Snacks')], default='SNACKS', max_length=20),
        ),
    ]
